org: franciscorafart
app: test-serverless
service: test-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
  testStuff:
    handler: testStuff.handler
